"""Added admisiion column in students

Revision ID: cd04af95ec6b
Revises: dce982a7e58d
Create Date: 2023-09-07 18:46:37.615813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd04af95ec6b'
down_revision: Union[str, None] = 'dce982a7e58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('admission_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'admission_id')
    # ### end Alembic commands ###
