"""Added Lessons and Teachers model

Revision ID: 20ab16febc06
Revises: 623813b56ccf
Create Date: 2023-09-08 09:15:19.407077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ab16febc06'
down_revision: Union[str, None] = '623813b56ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_lessons_student_id_students')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lessons_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('students', 'phone_number',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('teachers', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.add_column('teachers', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('teachers', 'subject_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('fk_teachers_student_id_students', 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'student_id')
    op.drop_column('teachers', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('teachers', sa.Column('student_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_teachers_student_id_students', 'teachers', 'students', ['student_id'], ['student_id'])
    op.alter_column('teachers', 'subject_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('teachers', 'phone')
    op.drop_column('teachers', 'teacher_id')
    op.alter_column('students', 'phone_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('lessons')
    # ### end Alembic commands ###
