"""renamed relationship for Student to teachers and subjects

Revision ID: 88c6f01516c7
Revises: 9edc3439db92
Create Date: 2023-09-06 23:43:07.715932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c6f01516c7'
down_revision: Union[str, None] = '9edc3439db92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
